### ISSUE TITLE
fatal error 'atomic' file not found

### ISSUE THREAD

**Issue by SopmmmodII** [microsoft/EVM-for-CCF#16]
root@ubiplab-ThinkPad-X1-Carbon-7th:/home/ubiplab/EvM-for-CCF/build# ninja
[89/215] Building CXX object CMakeFile...pto.host.dir/CCF/src/crypto/hash.cpp.o
FAILED: CMakeFiles/ccfcrypto.host.dir/CCF/src/crypto/hash.cpp.o 
/usr/bin/clang++-8  -DOE_API_VERSION=2 -DSERVICE_IDENTITY_CURVE_CHOICE_SECP384R1 -I../CCF/src -I../CCF/3rdparty/evercrypt-msr/evercrypt -I../CCF/3rdparty/evercrypt-msr/evercrypt/kremlin -isystem ../CCF/3rdparty -isystem ../CCF/3rdparty/evercrypt-msr -isystem ../CCF/3rdparty/msgpack-c -isystem ../CCF/3rdparty/flatbuffers/include -isystem . -O2 -g -DNDEBUG -fPIC   -fcolor-diagnostics -stdlib=libc++ -std=gnu++17 -MD -MT CMakeFiles/ccfcrypto.host.dir/CCF/src/crypto/hash.cpp.o -MF CMakeFiles/ccfcrypto.host.dir/CCF/src/crypto/hash.cpp.o.d -o CMakeFiles/ccfcrypto.host.dir/CCF/src/crypto/hash.cpp.o -c ../CCF/src/crypto/hash.cpp
In file included from ../CCF/src/crypto/hash.cpp:3:
In file included from ../CCF/src/crypto/hash.h:4:
../CCF/src/crypto/../ds/buffer.h:4:10: fatal error: 'atomic' file not found
#include <atomic>
         ^~~~~~~~
1 error generated.
[91/215] Building CXX object CMakeFile....host.dir/CCF/src/crypto/symmkey.cpp.o
FAILED: CMakeFiles/ccfcrypto.host.dir/CCF/src/crypto/symmkey.cpp.o 
/usr/bin/clang++-8  -DOE_API_VERSION=2 -DSERVICE_IDENTITY_CURVE_CHOICE_SECP384R1 -I../CCF/src -I../CCF/3rdparty/evercrypt-msr/evercrypt -I../CCF/3rdparty/evercrypt-msr/evercrypt/kremlin -isystem ../CCF/3rdparty -isystem ../CCF/3rdparty/evercrypt-msr -isystem ../CCF/3rdparty/msgpack-c -isystem ../CCF/3rdparty/flatbuffers/include -isystem . -O2 -g -DNDEBUG -fPIC   -fcolor-diagnostics -stdlib=libc++ -std=gnu++17 -MD -MT CMakeFiles/ccfcrypto.host.dir/CCF/src/crypto/symmkey.cpp.o -MF CMakeFiles/ccfcrypto.host.dir/CCF/src/crypto/symmkey.cpp.o.d -o CMakeFiles/ccfcrypto.host.dir/CCF/src/crypto/symmkey.cpp.o -c ../CCF/src/crypto/symmkey.cpp
In file included from ../CCF/src/crypto/symmkey.cpp:3:
In file included from ../CCF/src/crypto/symmkey.h:4:
../CCF/src/crypto/../ds/buffer.h:4:10: fatal error: 'atomic' file not found
#include <atomic>
         ^~~~~~~~
1 error generated.
[98/215] Building CXX object CMakeFiles/enclave_evm.dir/eEVM/src/processor.cpp.o
ninja: build stopped: subcommand failed.

**Comment by eddyashton** [comment]
The `atomic` header should be included with libc++. If the compiler can't find it, this probably means libc++ is not installed?

**Comment by SopmmmodII** [comment]
> The `atomic` header should be included with libc++. If the compiler can't find it, this probably means libc++ is not installed?

Thanks! I installed the libc++ library.
