### ISSUE TITLE
/bin/sh: 1: Syntax error: EOF in backquote substitution

### ISSUE THREAD

**Issue by SopmmmodII** [microsoft/EVM-for-CCF#17]
[195/215] Linking CXX shared library libevm4ccf.so
FAILED: libevm4ccf.so 
: && /usr/bin/clang++-8 -fPIC -O2 -g -DNDEBUG   -shared -Wl,-soname,libevm4ccf.so -o libevm4ccf.so CMakeFiles/evm4ccf.dir/CCF/src/enclave/main.cpp.o CMakeFiles/evm4ccf.dir/src/app/evm_for_ccf.cpp.o CMakeFiles/evm4ccf.dir/eEVM/src/disassembler.cpp.o CMakeFiles/evm4ccf.dir/eEVM/src/stack.cpp.o CMakeFiles/evm4ccf.dir/eEVM/src/transaction.cpp.o CMakeFiles/evm4ccf.dir/eEVM/src/util.cpp.o CMakeFiles/evm4ccf.dir/eEVM/src/processor.cpp.o CMakeFiles/evm4ccf.dir/ccf_t.cpp.o CMakeFiles/evm4ccf.dir/eEVM/3rdparty/intx/lib/intx/div.cpp.o  -nostdlib -nodefaultlibs -nostartfiles -Wl,--no-undefined -Wl,-Bstatic,-Bsymbolic,--export-dynamic,-pie libkeccak_enclave.a ` libccfcrypto.enclave.a libevercrypt.enclave.a liblua.enclave.a /opt/openenclave/lib/openenclave/enclave/liboeenclave.a /opt/openenclave/lib/openenclave/enclave/liboecryptombed.a /opt/openenclave/lib/openenclave/enclave/libmbedcrypto.a /opt/openenclave/lib/openenclave/enclave/libmbedx509.a /opt/openenclave/lib/openenclave/enclave/libmbedtls.a /opt/openenclave/lib/openenclave/enclave/liboelibcxx.a /opt/openenclave/lib/openenclave/enclave/liboelibc.a /opt/openenclave/lib/openenclave/enclave/liboesyscall.a /opt/openenclave/lib/openenclave/enclave/liboecore.a libsecp256k1.enclave.a libhttp_parser.enclave.a -nostdlib -nodefaultlibs -nostartfiles -Wl,--no-undefined -Wl,-Bstatic,-Bsymbolic,--export-dynamic,-pie && :

This problem occurs when running ninja command, Is this caused by quotation mark?

**Comment by eddyashton** [comment]
There's no backquotes in the CMake sources, so I've no idea how it's been inserted into your build command. Do you have a local modification to the repo that has added this?

**Comment by SopmmmodII** [comment]
> There's no backquotes in the CMake sources, so I've no idea how it's been inserted into your build command. Do you have a local modification to the repo that has added this?

Thanks! I checked the CMake sources and found that a backquote was added to the last line of _evm4ccf.app.cmake_,  but I don't know how it was added.
